### ISSUE TITLE
L2jServer JDK8

### ISSUE THREAD

**Issue by jcerutti** [nightw0lv/iTopZ-Java#1]
Hello, how are you?
I'm using a source L2jServer with JDK 8 and i've got this error when i try to compile, i know whats the problem, but cant update my project java to 14 without losing time haha

"class file has wrong version 58.0, should be 52.0"

wich quickfix do you recommend me ?

**Comment by nightw0lv** [comment]
> 
> 
> Hello, how are you?
> I'm using a source L2jServer with JDK 8 and i've got this error when i try to compile, i know whats the problem, but cant update my project java to 14 without losing time haha
> 
> "class file has wrong version 58.0, should be 52.0"
> 
> wich quickfix do you recommend me ?

L2jServer using JDK 14 not JDK 8 switch your project on JDK 14 version it will work by default, I believe it will solve it.

for information
- Java 8 uses major version 52
- Java 14 uses major version 58

Best way to do this is get the source and add it on l2jserver source.
Sources can be found here:
https://github.com/nightw0lv/iTopZ-Java/tree/master/HighFive/L2JServer/src/itopz/com

**Comment by jcerutti** [comment]
> > Hello, how are you?
> > I'm using a source L2jServer with JDK 8 and i've got this error when i try to compile, i know whats the problem, but cant update my project java to 14 without losing time haha
> > "class file has wrong version 58.0, should be 52.0"
> > wich quickfix do you recommend me ?
> 
> L2jServer using JDK 14 not JDK 8 switch your project on JDK 14 version it will work by default, I believe it will solve it.
> 
> for information
> 
> * Java 8 uses major version 52
> * Java 14 uses major version 58
> 
> Best way to do this is get the source and add it on l2jserver source.
> Sources can be found here:
> https://github.com/nightw0lv/iTopZ-Java/tree/master/HighFive/L2JServer/src/itopz/com

Thanks, i made a new jar for this version of l2jserver i have, works good so far

**Comment by nightw0lv** [comment]
Glad to hear it, feel free to share it if you want! :)
