### ISSUE TITLE
Consola iTopz

### ISSUE THREAD

**Issue by andrescespedest** [nightw0lv/iTopZ-Java#2]
Hello friend, when I try to open the server it gives me an error when I want to load the console I set the console configuration to false but it keeps giving an error. I understand that it is because I am on linux. Something can be implemented to prevent the graphical interface from firing.

**Comment by nightw0lv** [comment]
> 
> 
> Hello friend, when I try to open the server it gives me an error when I want to load the console I set the console configuration to false but it keeps giving an error. I understand that it is because I am on linux. Something can be implemented to prevent the graphical interface from firing.

Hello @dakpower, its true I could not find the time to test in linux without GUI it is tested on windows only but feel free take the source and remove the GUI totally from the system I have build a guide to do that you need a few steps, then press delete and start removing the calls until I can find the time to solve it.

here is the guide
https://github.com/nightw0lv/iTopZ-Java/tree/master/Guide
